var p1 = new Product();
var p2 = new Product();
var p3 = new Product();
var p4 = new Product();
var p5 = new Product();
p1.input();
p2.input();
p3.input();
p4.input();
p5.input();
Product.Title();
p1.print(1);
p2.print(2);
p3.print(3);
p4.print(4);
p5.print(5);